routes/web.php
<?php
//Route::redirect('/admin', 'admin/admin');

Auth::routes(['register' => false]);
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
// Change Password Routes...

Route::get('/', 'KonsultasiController@index')->name('home');

Route::get('/sub_pendidikan', 'KonsultasiController@sub_pendidikan');



Route::get('save-perjanjian/konsul_lansung', 'KonsultasiController@konsul_lansung');

Route::get('/sub-kategori/{id}', 'KonsultasiController@sub_kategori');

Route::get('/home-test', 'KonsultasiController@index_test')->name('home_test');

Route::get('/layanan-konsultasi', 'KonsultasiController@layanan_konsultasi')->name('layanan_konsultasi');

Route::get('/sukses/{id_laporan_klien}/{name}', 'KonsultasiController@sukses')->name('sukses');
//Route::post('/sukses/{id_laporan_klien}/{name}', 'KonsultasiController@sukses');

Route::get('/profil-psikologi/{id_psikologi}', 'KonsultasiController@profil_psikologi');
Route::get('/bayar','BayarController@render');

Route::get('/test','KonsultasiController@test');

Route::get('/kategori-konsul', 'KonsultasiController@kategoriKonsul')->name('kategori-konsul');
Route::get('/kategori-konsul/order/{name_konsul}', 'KonsultasiController@orderKonsul')->name('order');

Route::get('/masuk-otp', 'KonsultasiController@masuk_otp')->name('masukotp');
Route::post('/masuk-otp', 'KonsultasiController@masuk_otp_post');

Route::get('/pilih-tanggal-order/{tanggal}/{id_psikologi}', 'KonsultasiController@pilihTanggalOrder');
Route::get('/kategori-konsul/order/perjanjian/{id_psikologi}/{name}', 'KonsultasiController@perjanjian');

Route::get('/cari-psikologi/{di_sub_kategori}', 'KonsultasiController@cari_psikologi');


Route::get('/kategori', 'KonsultasiController@kategori');

Route::get('/cari-psikolog', 'KonsultasiController@psikolog');



Route::get('/save-perjanjian/{name}', 'KonsultasiController@savePerjanjian')->name('order.konsul');

Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
Route::post('/login-user', 'AuthController@login_user');
Route::post('/register-user', 'AuthController@register_user');

Route::middleware('guest')->group(function() {
    Route::get('/register', 'AuthController@register')->name('register');
    Route::post('/register', 'AuthController@register_post');

    Route::get('/otp/{otp}', 'AuthController@otp');

    Route::get('/register-psikologi', 'AuthController@registerPsikologi')->name('registerPsikologi');
    Route::post('/register-psikologi', 'AuthController@register_psikologi_post');

    Route::get('/psikolog', 'AuthController@loginPsikologi')->name('psikolog');
    Route::post('/psikolog', 'AuthController@loginPsikologi_post'); 
});
Route::group(['middleware' => ['auth'], 'prefix' => 'klien', 'as' => 'klien.'], function () {
    Route::get('/data-profil', 'Klien\KlienController@data_profil')->name('data_profil');
    Route::get('/update-profil', 'Klien\KlienController@update_profil');
    Route::post('/update-profil', 'Klien\KlienController@update_profil_post');
    Route::get('/ubah-password', 'Klien\KlienController@ubah_password');
    Route::get('/pemesanan/{name}', 'Klien\KlienController@pemesanan');
    Route::post('/pemesanan/{name}', 'Klien\KlienController@pemesanan');
    Route::get('/bayar','Klien\KlienController@bayar');
});
Route::group(['middleware' => ['auth'], 'prefix' => 'psikolog', 'as' => 'psikolog.'], function () {

    Route::get('/profil', 'Psikolog\PsikologController@profil');

    Route::post('/upload-img', 'Psikolog\PsikologController@upload_img');

    Route::get('/data-profil', 'Psikolog\PsikologController@data_profil')->name('data_profil_psikolog');
    
    Route::post('/update-profil-user', 'Psikolog\PsikologController@update_profil_user_post');

    Route::get('/update-profil', 'Psikolog\PsikologController@update_profil')->name('update.profil');
    Route::post('/update-profil', 'Psikolog\PsikologController@update_profil_post');

    Route::get('/ubah-password', 'Psikolog\PsikologController@ubah_password');

    Route::get('/kategori', 'Psikolog\PsikologController@kategori')->name('kategori');
    Route::get('/delete/{id}', 'Psikolog\PsikologController@kategoriDelete')->name('kategoriDelete');

    Route::get('/create-kategori', 'Psikolog\PsikologController@create_kategori')->name('create_kategori');
    Route::post('/create-kategori', 'Psikolog\PsikologController@create_kategori_post');

    Route::get('/data_klien', 'Psikolog\PsikologController@dataKlien')->name('data_klien');

    Route::get('/jadwal-konsul', 'Psikolog\PsikologController@jadwal_konsul')->name('jadwal_konsul');
    Route::get('/create-jadwal', 'Psikolog\PsikologController@create_jadwal');

    Route::get('/create-jam/{jam}/{hari}', 'Psikolog\PsikologController@create_jam');
    Route::get('/delete-jam/{jam}/{hari}', 'Psikolog\PsikologController@delete_jam');
    
    Route::get('/ambil-jadwal', 'Psikolog\PsikologController@ambil_jadwal'); 
    
});
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    
    Route::post('/save-perjanjian/{name}', 'KonsultasiController@savePerjanjian');
    Route::get('/invoice/{id_laporan_klien}', 'KonsultasiController@invoice')->name('invoice.klien');
    Route::post('/invoice/{id_laporan_klien}', 'KonsultasiController@invoice');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/save-perjanjian/{name}', 'KonsultasiController@savePerjanjian')->name('order.konsul');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('admin');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');

    Route::resource('transaksi', 'Admin\TransaksiController');
    Route::post('transaksi_mass_destroy', ['uses' => 'Admin\TransaksiController@massDestroy', 'as' => 'transaksi.mass_destroy']);
    Route::put('transaksi/{id}/restore', ['as' => 'TransaksiController.restore', 'uses' => 'Admin\TransaksiController@restore']);
    Route::put('transaksi/{id}/forcedelete', ['as' => 'TransaksiController.forcedelete', 'uses' => 'Admin\TransaksiController@forcedelete']);
    
    Route::get('/transaksi/views/{id}', 'Admin\TransaksiController@view')->name('transaksi.views');
    Route::get('/transaksi/detail/{id}', 'Admin\TransaksiController@detail')->name('transaksi.detail');
    Route::get('/transaksi/data-suda-bayar/{id}', 'Admin\TransaksiController@data_suda_bayar');

    Route::get('/kategori-psikolog', 'Admin\KategoriPsikologController@index');
    Route::get('/kategori-psikolog/views/{id}', 'Admin\KategoriPsikologController@view');

    Route::get('/pendapatan-psikolog', 'Admin\PendapatanPsikologController@index');
    Route::get('/pendapatan/views/{id}', 'Admin\PendapatanPsikologController@view')->name('pendapatan.views');
    Route::get('/pendapatan/detail', 'Admin\PendapatanPsikologController@detail');

    Route::get('/permintaan-psikolog', 'Admin\PermintaanPsikologController@index')->name('permintan.psikolog');
    Route::get('/permintaan-psikolog/terima/{id}', 'Admin\PermintaanPsikologController@terima');
    Route::get('/permintaan-psikolog/tolak/{id}', 'Admin\PermintaanPsikologController@tolak');
    Route::get('/permintaan-psikolog/profil', 'Admin\PermintaanPsikologController@profil');
});

// Route::group(['prefix' => 'agen', 'middleware' => ['AdminMiddleware']], function() {
//     Route::resource('/pemesanan', 'Admin\OrderController', ['as' => 'admin']);
// });

app/Transaksi.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
/**
 * Class Team
 *
 * @package App
 * @property string $code
*/
class Transaksi extends Model
{
    protected $table = "transaksi";
    protected $primaryKey = 'id_transaksi';

    public function klien()
    {
        return $this->hasOne('App\User','id','id_user');
    }

    public function psikologi(){
        return $this->hasOne('App\Psikologi','id_psikologi','id_psikologi');
    }

    public function subKategori(){
        return $this->hasOne('App\SubKategori','id_sub_kategori','id_kategori_konsul');
    }
    public function media(){
        return $this->hasOne('App\Media','id_media','id_media');
    }

    public function laporanKlien(){
        return $this->hasOne('App\LaporanKlien','id_transaksi','id_transaksi');
    }
    public function jadwalKonsul(){
        return $this->hasOne('App\JadwalKonsul','id_jadwal_konsul','id_jadwal_konsul');
    }
    public static function kasih_reting(){
        $cek = array();
        if(!empty(Auth::user()->id)){
            $cek = Transaksi::where('status_bayar','settlement')
            ->leftJoin('media','media.id_media','=','transaksi.id_media')
            ->where('jadwal','<', date('Y-m-d'))
            ->where('reting',null)
            ->where('id_user', Auth::user()->id)
            ->orderBy('jadwal','asc')
            ->first();
        }
        return $cek;
    }
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use App\Biodata;
use App\Kategori;
use App\LaporanKlien;
use App\LaporanPsikologi;
use App\Lib;
use App\Media;
use App\Psikologi;
use App\PsikologiKategoriKonsul;
use App\Transaksi;
use App\User;
use Illuminate\Http\Request;
use ElephantIO\Client;
use ElephantIO\Engine\SocketIO\Version2X;
use DB;
use DateTime;
use Illuminate\Support\Facades\Auth;

class TransaksiController extends Controller
{
    public function cek_transaksi()
    {
        date_default_timezone_set('Asia/Jakarta');
        $cek = Transaksi::where('status_bayar','settlement')
                ->leftJoin('media','media.id_media','=','transaksi.id_media')
                ->where('jadwal','>=', date('Y-m-d'))
                ->where('reminder',null)
                ->get();
        foreach($cek as $cek1){
            $awal  = new \DateTime($cek1->jadwal.' '.$cek1->jam); //waktu awal
            $akhir = new \DateTime(date('Y-m-d H:i:s')); //waktu akhir
            $jumlah_jadwal = $awal->diff($akhir);
            
            if($jumlah_jadwal->h == 0 && $jumlah_jadwal->d == 0 && $cek1->reminder == ''){
                $transaksi = Transaksi::where('id_transaksi',$cek1->id_transaksi)->first();
                $transaksi->reminder = 1;
                $transaksi->save();

                $biodata1 = Biodata::where('id_user',$transaksi->id_user)->first();

                $psikologi = Psikologi::
                            leftJoin('biodata','biodata.id_biodata','=','psikologi.id_biodata')  
                            ->where('psikologi.id_psikologi',$transaksi->id_psikologi)->first();
                
                $kategori = DB::table('kategori_konsul_sub_kategori')->where('id_sub_kategori',
                $transaksi->id_kategori_konsul)->leftJoin('kategori_konsul','kategori_konsul.id_kategori_konsul','=','kategori_konsul_sub_kategori.id_kategori_konsul')
                ->first();

                $kategori_sub = DB::table('sub_kategori')->where('id_sub_kategori',
                $transaksi->id_kategori_konsul)
                ->first();

                $message = "Yth : ".$biodata1->nama. "\n\nReminder:\nJangan lupa ya hari ini kamu ada jawal konsultasi dengan psikolog 1 jam lagi.\n\nNama klien : ".$biodata1->nama."\nTanggal Konsultasi: ".date('d-M-Y', strtotime(date($cek1->jadwal)))."\nJam Konsultasi : ".$cek1->jam."\nNama Psikolog : ".$psikologi->nama. "\nMedia : ".$cek1->nama_media."\nKategori Konsultasi : ".$kategori->nama_konsul."\nSub Kategori : ".$kategori_sub->nama_sub_kategori."\nDetail Konsultasi : ".$transaksi->masalah."\n\nHarap untuk dapat melakukan konsultasi sesuai jadwal";
                $version = new Version2X("http://109.106.255.28:8000/");
                $client = new Client($version);
                $client->initialize();
                $client->emit('send data', ['nomor' => $biodata1->no_hp, 'message'=>$message,'jml_nomor' => 1,'otp'=>1]);
                $client->close();

                $message = "Yth : ".$psikologi->nama. "\n\nReminder:\nJangan lupa ya hari ini kamu ada jawal konsultasi dengan klien 1 jam lagi.\n\nNama klien : ".$biodata1->nama."\nTanggal Konsultasi: ".date('d-M-Y', strtotime(date($cek1->jadwal)))."\nJam Konsultasi : ".$cek1->jam."\nNama Psikolog : ".$psikologi->nama. "\nMedia : ".$cek1->nama_media."\nKategori Konsultasi : ".$kategori->nama_konsul."\nSub Kategori : ".$kategori_sub->nama_sub_kategori."\nDetail Konsultasi : ".$transaksi->masalah."\n\nHarap untuk dapat melakukan konsultasi sesuai jadwal";

                $version = new Version2X("http://109.106.255.28:8000/");
                $client = new Client($version);
                $client->initialize();
                $client->emit('send data', ['nomor' => $psikologi->no_hp, 'message'=>$message,'jml_nomor' => 1,'otp'=>1]);
                $client->close();
            }
        }
        
        $cek = Transaksi::where('status_bayar','settlement')
                ->leftJoin('media','media.id_media','=','transaksi.id_media')
                ->where('jadwal','<', date('Y-m-d'))
                ->where('notif_reting',null)
                ->get();
        foreach($cek as $cek1){
            $transaksi = Transaksi::where('id_transaksi',$cek1->id_transaksi)->first();
            $transaksi->notif_reting = 1;
            $transaksi->save();

            $biodata1 = Biodata::where('id_user',$transaksi->id_user)->first();

            $psikologi = Psikologi::
                        leftJoin('biodata','biodata.id_biodata','=','psikologi.id_biodata')  
                        ->where('psikologi.id_psikologi',$transaksi->id_psikologi)->first();

            $message = "Yth : ".$biodata1->nama. "\nKasih reting konsul anda untuk psikolog ".$psikologi->nama." dengan mengklik link https://konsul.yukbiz.com terimakasih";
            $version = new Version2X("http://109.106.255.28:8000/");
            $client = new Client($version);
            $client->initialize();
            $client->emit('send data', ['nomor' => $biodata1->no_hp, 'message'=>$message,'jml_nomor' => 1,'otp'=>1]);
            $client->close();
        }
    }
    public function reting()
    {
        echo "d";
        exit;
    }
    public function opt_update(){
        $cek_token = User::where('id',$_GET['id'])->where('aktif',0)->first();
        $cek_token->otp = rand(10,10000);
        $cek_token->save();
        session()->flash('success','OTP di kirim ulang ke Whatsapp anda');
    }
}

resources/views/admin/transaksi/data_views.blade.php
                    @if (count($transaksi) > 0)
                        @foreach ($transaksi as $transaksi)
                            <tr data-entry-id="{{ $transaksi->id_psikologi }}">
                                
                                    <td></td>
                                <td> {{ $transaksi->psikologi->nama}} <label onclick="lihatPerjanjian('<?= $transaksi->id_transaksi ?>')" class="btn btn-xs btn-info" data-toggle="modal" data-target="#myModal">Lihat</label></td>
                                <td>{{ $transaksi->klien->name}}</td>
                                <td>{{ $transaksi->no_transaksi}}</td>
                                <td>{{ $transaksi->subKategori->nama_sub_kategori}}</td>
                                <td>{{ $transaksi->media->nama_media}}</td>
                                <td>{{ $transaksi->jadwal}}</td>
                                <td>{{ $transaksi->jam}}</td>
                                <td>{{ $transaksi->masalah}}</td>
                                <td>{{ $transaksi->laporanKlien->total_konsul}}</td>
                                @if($transaksi->status_bayar == 'pending')
                                    <td>Belum Bayar</td>
                                @elseif($transaksi->status_bayar == 'settlement')
                                    <td>Sudah Dibayar</td>
                                @else
                                    <td>{{$transaksi->status_bayar}}</td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="10">Data Tidak Ada</td>
                        </tr>
                    @endif

resources/views/admin/transaksi/index.blade.php
<?php
use App\Transaksi;
?>
@extends('layouts.admin1')

@section('content')
    <h3 class="page-title">Transaksi</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            
        </div>

        <div class="card-body">
            <div class="row">
            @foreach ($transaksi as $transaksi2)
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-aqua">
                            <img src="{{asset($transaksi2->psikologi->foto)}}">
                        </span>
                        <?php
                            $total_tranksasi_bayar = Transaksi::select('id_psikologi')->where('status_bayar','settlement')->where('id_psikologi',$transaksi2->id_psikologi)->where('jadwal','>',date('Y-m-d'))->groupBy('id_psikologi')->count();
                        ?>
                        <div class="info-box-content">
                            <span class="info-box-text">{{ $transaksi2->psikologi->nama}}</span>
                                <label></label><span class="info-box-number">{{$total_tranksasi_bayar}} <small>Akan Berlangsung</small></span>
                        </div>
                    <!-- /.info-box-content -->
                    </div>
                </div>
                <!-- /.info-box -->
            @endforeach
            </div>
        </div>

            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-Permission">
                    <thead>
                        <tr>
                        <th width="10">

                        </th>
                            <th>Psikolog</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        @if (count($transaksi) > 0)
                            @foreach ($transaksi as $transaksi1)
                                <tr data-entry-id="{{ $transaksi1->id_psikologi }}">
                                    
                                        <td></td>
                                    <td>{{ $transaksi1->psikologi->nama}}</td>
                                    <td>
                                        <a href="{{ route('admin.transaksi.views',[$transaksi1->id_psikologi]) }}" class="btn btn-xs btn-info">Lihat Transaksi</a>                                    
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.transaksi.mass_destroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Permission:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/transaksi/views.blade.php
<?php
use App\Lib;
?>
@extends('layouts.admin1')

@section('content')
    <h3 class="page-title">Transaksi</h3>

    <div class="panel panel-default">
    <div calss="row">
            <div class="col-lg-4">
                <!-- Widget: user widget style 1 -->
                <div class="box box-widget widget-user">
                    <!-- Add the bg color to the header using any of the bg-* classes -->
                    <div class="widget-user-header bg-black" style="background: url('../dist/img/photo1.png') center center;">
                        <h3 class="widget-user-username">{{$psikolog->nama}}</h3>
                        <h5 class="widget-user-desc">Psikolog</h5>
                        </div>
                        <div class="widget-user-image">
                        <img class="img-circle" src="{{asset($psikolog->foto)}}" alt="User Avatar">
                        </div>
                        <div class="box-footer">
                        <div class="row">
                            <div class="col-sm-4 border-right">
                            <div class="description-block">
                                <h5 class="description-header">{{$total_tranksasi_bayar}}</h5>
                                <span class="description-text">Perjanjian</span>
                            </div>
                            <!-- /.description-block -->
                            </div>
                            <!-- /.col -->
                            <div class="col-sm-4 border-right">
                            <div class="description-block">
                                <h5 class="description-header">{{$total_tranksasi_bayar_sudah}}</h5>
                                <span class="description-text">Perjanjian Sukses</span>
                            </div>
                            <!-- /.description-block -->
                            </div>
                            <!-- /.col -->
                            <div class="col-sm-4">
                            <div class="description-block">
                                <h5 class="description-header">{{$pending}}</h5>
                                <span class="description-text">Belum Bayar</span>
                            </div>
                            <!-- /.description-block -->
                            </div>
                            <!-- /.col -->
                        </div>
                    <!-- /.row -->
                    </div>
                </div>
                <!-- /.widget-user -->
            </div>

            <div class="col-lg-4">
                <div class="btn-group btn-group-lg">
                    <button onclick="dataTransaksi('all')" type="button" class="btn btn-primary">All</button>
                    <button onclick="dataTransaksi('settlement')" type="button" class="btn btn-primary">Sudah bayar</button>
                    <button onclick="dataTransaksi('pending')" type="button" class="btn btn-primary">Pending</button>
                    <button onclick="dataTransaksi('expire')" type="button" class="btn btn-primary">Expired</button>
                </div> 
            </div>

        </div>

        <div class="card-body" >
        

        <div class="panel-heading">
            
        </div>

            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-Permission">
                    <thead>
                        <tr>
                        <th width="10">

                        </th>
                            <th>Psikolog</th>
                            <th>Nama Klien</th>
                            <th>No Transaksi</th>
                            <th>Kategori Konsul</th>
                            <th>Media</th>
                            <th>Jadwal</th>
                            <th>Jam</th>
                            <th>Masalah</th>
                            <th>Total Konsul</th>
                            <th>Status</th>
                            
                        </tr>
                    </thead>
                    
                    <tbody id="dataTransaksi">
                        @if (count($transaksi) > 0)
                            @foreach ($transaksi as $transaksi)
                                <tr data-entry-id="{{ $transaksi->id_psikologi }}">
                                    
                                        <td></td>
                                    <td> {{ $transaksi->psikologi->nama}} <label onclick="lihatPerjanjian('<?= $transaksi->id_transaksi ?>')" class="btn btn-xs btn-info" data-toggle="modal" data-target="#myModal">Lihat</label></td>
                                    <td>{{ $transaksi->klien->name}}</td>
                                    <td>{{ $transaksi->no_transaksi}}</td>
                                    <td>{{ $transaksi->subKategori->nama_sub_kategori}}</td>
                                    <td>{{ $transaksi->media->nama_media}}</td>
                                    <td>{{ $transaksi->jadwal}}</td>
                                    <td>{{ $transaksi->jam}}</td>
                                    <td>{{ $transaksi->masalah}}</td>
                                    <td><?= Lib::rupiah($transaksi->laporanKlien->total_konsul) ?></td>
                                    @if($transaksi->status_bayar == 'pending')
                                        <td>Belum Bayar</td>
                                    @elseif($transaksi->status_bayar == 'settlement')
                                        <td>Sudah Dibayar</td>
                                    @else
                                        <td>{{$transaksi->status_bayar}}</td>
                                    @endif
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Detail Transaksi</h4>
      </div>
      <div class="modal-body" id="detail_transaksi">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
@endsection
@section('scripts')
@parent
<script>
function dataTransaksi(id){
    $('#dataTransaksi').load('{{url("admin/transaksi/views")}}/<?=$id?>?status='+id, function(e) {});
}
function lihatPerjanjian(id){
    $('#detail_transaksi').load('{{url("admin/transaksi/detail")}}/'+id, function(e) {});
}
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.transaksi.mass_destroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Permission:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection