routes/web.php
<?php
//Route::redirect('/admin', 'admin/admin');

Auth::routes(['register' => false]);
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
// Change Password Routes...

Route::get('/', 'KonsultasiController@index')->name('home');

Route::get('/sub_pendidikan', 'KonsultasiController@sub_pendidikan');



Route::get('save-perjanjian/konsul_lansung', 'KonsultasiController@konsul_lansung');

Route::get('/sub-kategori/{id}', 'KonsultasiController@sub_kategori');

Route::get('/home-test', 'KonsultasiController@index_test')->name('home_test');

Route::get('/layanan-konsultasi', 'KonsultasiController@layanan_konsultasi')->name('layanan_konsultasi');

Route::get('/sukses/{id_laporan_klien}/{name}', 'KonsultasiController@sukses')->name('sukses');
//Route::post('/sukses/{id_laporan_klien}/{name}', 'KonsultasiController@sukses');

Route::get('/profil-psikologi/{id_psikologi}', 'KonsultasiController@profil_psikologi');
Route::get('/bayar','BayarController@render');

Route::get('/test','KonsultasiController@test');

Route::get('/kategori-konsul', 'KonsultasiController@kategoriKonsul')->name('kategori-konsul');
Route::get('/kategori-konsul/order/{name_konsul}', 'KonsultasiController@orderKonsul')->name('order');

Route::get('/masuk-otp', 'KonsultasiController@masuk_otp')->name('masukotp');
Route::post('/masuk-otp', 'KonsultasiController@masuk_otp_post');

Route::get('/pilih-tanggal-order/{tanggal}/{id_psikologi}', 'KonsultasiController@pilihTanggalOrder');
Route::get('/kategori-konsul/order/perjanjian/{id_psikologi}/{name}', 'KonsultasiController@perjanjian');

Route::get('/cari-psikologi/{di_sub_kategori}', 'KonsultasiController@cari_psikologi');


Route::get('/kategori', 'KonsultasiController@kategori');

Route::get('/cari-psikolog', 'KonsultasiController@psikolog');



Route::get('/save-perjanjian/{name}', 'KonsultasiController@savePerjanjian')->name('order.konsul');

Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
Route::post('/login-user', 'AuthController@login_user');
Route::post('/register-user', 'AuthController@register_user');

Route::middleware('guest')->group(function() {
    Route::get('/register', 'AuthController@register')->name('register');
    Route::post('/register', 'AuthController@register_post');

    Route::get('/otp/{otp}', 'AuthController@otp');

    Route::get('/register-psikologi', 'AuthController@registerPsikologi')->name('registerPsikologi');
    Route::post('/register-psikologi', 'AuthController@register_psikologi_post');

    Route::get('/psikolog', 'AuthController@loginPsikologi')->name('psikolog');
    Route::post('/psikolog', 'AuthController@loginPsikologi_post'); 
});
Route::group(['middleware' => ['auth'], 'prefix' => 'klien', 'as' => 'klien.'], function () {
    Route::get('/data-profil', 'Klien\KlienController@data_profil')->name('data_profil');
    Route::get('/update-profil', 'Klien\KlienController@update_profil');
    Route::post('/update-profil', 'Klien\KlienController@update_profil_post');
    Route::get('/ubah-password', 'Klien\KlienController@ubah_password');
    Route::get('/pemesanan/{name}', 'Klien\KlienController@pemesanan');
    Route::post('/pemesanan/{name}', 'Klien\KlienController@pemesanan');
    Route::get('/bayar','Klien\KlienController@bayar');
});
Route::group(['middleware' => ['auth'], 'prefix' => 'psikolog', 'as' => 'psikolog.'], function () {

    Route::get('/profil', 'Psikolog\PsikologController@profil');

    Route::post('/upload-img', 'Psikolog\PsikologController@upload_img');

    Route::get('/data-profil', 'Psikolog\PsikologController@data_profil')->name('data_profil_psikolog');
    
    Route::post('/update-profil-user', 'Psikolog\PsikologController@update_profil_user_post');

    Route::get('/update-profil', 'Psikolog\PsikologController@update_profil')->name('update.profil');
    Route::post('/update-profil', 'Psikolog\PsikologController@update_profil_post');

    Route::get('/ubah-password', 'Psikolog\PsikologController@ubah_password');

    Route::get('/kategori', 'Psikolog\PsikologController@kategori')->name('kategori');
    Route::get('/delete/{id}', 'Psikolog\PsikologController@kategoriDelete')->name('kategoriDelete');

    Route::get('/create-kategori', 'Psikolog\PsikologController@create_kategori')->name('create_kategori');
    Route::post('/create-kategori', 'Psikolog\PsikologController@create_kategori_post');

    Route::get('/data_klien', 'Psikolog\PsikologController@dataKlien')->name('data_klien');

    Route::get('/jadwal-konsul', 'Psikolog\PsikologController@jadwal_konsul')->name('jadwal_konsul');
    Route::get('/create-jadwal', 'Psikolog\PsikologController@create_jadwal');

    Route::get('/create-jam/{jam}/{hari}', 'Psikolog\PsikologController@create_jam');
    Route::get('/delete-jam/{jam}/{hari}', 'Psikolog\PsikologController@delete_jam');
    
    Route::get('/ambil-jadwal', 'Psikolog\PsikologController@ambil_jadwal'); 
    
});
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    
    Route::post('/save-perjanjian/{name}', 'KonsultasiController@savePerjanjian');
    Route::get('/invoice/{id_laporan_klien}', 'KonsultasiController@invoice')->name('invoice.klien');
    Route::post('/invoice/{id_laporan_klien}', 'KonsultasiController@invoice');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/save-perjanjian/{name}', 'KonsultasiController@savePerjanjian')->name('order.konsul');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('admin');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');

    Route::resource('transaksi', 'Admin\TransaksiController');
    Route::post('transaksi_mass_destroy', ['uses' => 'Admin\TransaksiController@massDestroy', 'as' => 'transaksi.mass_destroy']);
    Route::put('transaksi/{id}/restore', ['as' => 'TransaksiController.restore', 'uses' => 'Admin\TransaksiController@restore']);
    Route::put('transaksi/{id}/forcedelete', ['as' => 'TransaksiController.forcedelete', 'uses' => 'Admin\TransaksiController@forcedelete']);
    
    Route::get('/transaksi/views/{id}', 'Admin\TransaksiController@view')->name('transaksi.views');
    Route::get('/transaksi/detail/{id}', 'Admin\TransaksiController@detail')->name('transaksi.detail');
    Route::get('/transaksi/data-suda-bayar/{id}', 'Admin\TransaksiController@data_suda_bayar');

    Route::get('/kategori-psikolog', 'Admin\KategoriPsikologController@index');
    Route::get('/kategori-psikolog/views/{id}', 'Admin\KategoriPsikologController@view');

    Route::get('/pendapatan-psikolog', 'Admin\PendapatanPsikologController@index');
    Route::get('/pendapatan/views/{id}', 'Admin\PendapatanPsikologController@view')->name('pendapatan.views');
    Route::get('/pendapatan/detail', 'Admin\PendapatanPsikologController@detail');

    Route::get('/permintaan-psikolog', 'Admin\PermintaanPsikologController@index')->name('permintan.psikolog');
    Route::get('/permintaan-psikolog/terima/{id}', 'Admin\PermintaanPsikologController@terima');
    Route::get('/permintaan-psikolog/tolak/{id}', 'Admin\PermintaanPsikologController@tolak');
    Route::get('/permintaan-psikolog/profil', 'Admin\PermintaanPsikologController@profil');
});

// Route::group(['prefix' => 'agen', 'middleware' => ['AdminMiddleware']], function() {
//     Route::resource('/pemesanan', 'Admin\OrderController', ['as' => 'admin']);
// });

resources/views/admin/pendapatan/detail.blade.php
<?php
    use App\Transaksi;
    use App\LaporanKlien;
    use App\Lib;
?>
<div class="row">
    @foreach ($transaksi as $transaksi2)
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-aqua">
                    <img src="{{asset($transaksi2->psikologi->foto)}}">
                </span>
                <?php
                    $total_tranksasi_bayar = LaporanKlien::select(DB::raw('SUM(total_konsul) as total'), 'laporan_klien.id_psikologi as id_psikologi')->leftJoin('transaksi','transaksi.id_transaksi','=','laporan_klien.id_transaksi')->where('status_bayar','settlement')->where('laporan_klien.id_psikologi',$transaksi2->id_psikologi)
                    ->where('jadwal','>=',$dateForm)
                    ->where('jadwal','<=',$dateTo)
                    ->groupBy('laporan_klien.id_psikologi')->get();

                    if(!empty($total_tranksasi_bayar[0]['total'])){
                        $total = $total_tranksasi_bayar[0]['total'];
                    }else{
                        $total = '0';
                    }
                ?>
                <div class="info-box-content">
                    <span class="info-box-text">{{ $transaksi2->psikologi->nama}}</span>

                        <label></label><span class="info-box-number"><?= Lib::rupiah($total) ?> <small>Total Pendapatan</small></span>
                </div>
            <!-- /.info-box-content -->
            </div>
        </div>
        <!-- /.info-box -->
    @endforeach
</div>

<div class="table-responsive">
    <table class=" table table-bordered table-striped table-hover datatable datatable-Permission">
        <thead>
            <tr>
            <th width="10">

            </th>
                <th>Psikolog</th>
                <th>Nama Klien</th>
                <th>No Transaksi</th>
                <th>Kategori Konsul</th>
                <th>Media</th>
                <th>Jadwal</th>
                <th>Jam</th>
                <th>Masalah</th>
                <th>Total Konsul</th>
                <th>Status</th>
                
            </tr>
        </thead>
        
        <tbody id="dataTransaksi">
            @if (count($list) > 0)
                @foreach ($list as $list)
                    <tr data-entry-id="{{ $list->id_psikologi }}">
                        
                            <td></td>
                        <td> {{ $list->psikologi->nama}} <label onclick="lihatPerjanjian('<?= $list->id_transaksi ?>')" class="btn btn-xs btn-info" data-toggle="modal" data-target="#myModal">Lihat</label></td>
                        <td>{{ $list->klien->name}}</td>
                        <td>{{ $list->no_transaksi}}</td>
                        <td>{{ $list->subKategori->nama_sub_kategori}}</td>
                        <td>{{ $list->media->nama_media}}</td>
                        <td>{{ $list->jadwal}}</td>
                        <td>{{ $list->jam}}</td>
                        <td>{{ $list->masalah}}</td>
                        <td><?= Lib::rupiah($list->laporanKlien->total_konsul) ?></td>
                        @if($list->status_bayar == 'pending')
                            <td>Belum Bayar</td>
                        @elseif($list->status_bayar == 'settlement')
                            <td>Sudah Dibayar</td>
                        @else
                            <td>{{$list->status_bayar}}</td>
                        @endif
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                </tr>
            @endif
        </tbody>
    </table>
</div>

resources/views/admin/pendapatan/index.blade.php
<?php
use App\Transaksi;
use App\LaporanKlien;
use App\Lib;
?>
@extends('layouts.admin1')

@section('content')
    <h3 class="page-title">Transaksi</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            
        </div>

        <div class="card-body">
            <div class="row">
            @foreach ($transaksi as $transaksi2)
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-aqua">
                            <img src="{{asset($transaksi2->psikologi->foto)}}">
                        </span>
                        <?php
                            $total_tranksasi_bayar = LaporanKlien::select(DB::raw('SUM(total_konsul) as total'), 'laporan_klien.id_psikologi as id_psikologi')->leftJoin('transaksi','transaksi.id_transaksi','=','laporan_klien.id_transaksi')->where('status_bayar','settlement')->where('laporan_klien.id_psikologi',$transaksi2->id_psikologi)->groupBy('laporan_klien.id_psikologi')->get();

                            if(!empty($total_tranksasi_bayar[0]['total'])){
                                $total = $total_tranksasi_bayar[0]['total'];
                            }else{
                                $total = '0';
                            }
                        ?>
                        <div class="info-box-content">
                            <span class="info-box-text">{{ $transaksi2->psikologi->nama}}</span>

                                <label></label><span class="info-box-number"><?= Lib::rupiah($total) ?> <small>Total Pendapatan</small></span>
                        </div>
                    <!-- /.info-box-content -->
                    </div>
                </div>
                <!-- /.info-box -->
            @endforeach
            </div>
        </div>

            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-Permission">
                    <thead>
                        <tr>
                        <th width="10">

                        </th>
                            <th>Psikolog</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        @if (count($transaksi) > 0)
                            @foreach ($transaksi as $transaksi1)
                                <tr data-entry-id="{{ $transaksi1->id_psikologi }}">
                                    
                                        <td></td>
                                    <td>{{ $transaksi1->psikologi->nama}}</td>
                                    <td>
                                        <a href="{{ route('admin.pendapatan.views',[$transaksi1->id_psikologi]) }}" class="btn btn-xs btn-info">Lihat Pendapatan</a>                                    
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.transaksi.mass_destroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Permission:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/pendapatan/views.blade.php
<?php
use App\Transaksi;
use App\LaporanKlien;
use App\Lib;
?>
@extends('layouts.admin2')

@section('content')




<div class="col-md-12">
<!-- general form elements -->
<div class="box box-primary">
<div class="box-header with-border">
    <h3 class="box-title">Lihat Pendapatan</h3>
</div>


    <div class="box-body">
        <div class="form-group">
            <label for="exampleInputEmail1">Pilih Range Tanggal</label>
            <input onchange="pilihTanggal()" type="text" class="form-control" name="daterange" value="" />
            <input type="text" hidden class="form-control" id="dateForm" name="dateForm" value="" />
            <input type="text" hidden class="form-control" id="dateTo" name="dateTo" value="" />
        </div>
        <div class="form-group" id="dataPendapatan">
            
        </div>
    </div>
          <!-- /.box -->
    <!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Detail Transaksi</h4>
      </div>
      <div class="modal-body" id="detail_transaksi">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
@endsection
<script>
    function pilihTanggal(){
        var dateForm = $('#dateForm').val();
        var dateTo = $('#dateTo').val();
        $('#dataPendapatan').load('{{url("admin/pendapatan/detail")}}?id=<?= $id ?>&dateForm='+dateForm+'&dateTo='+dateTo, function(e) {});
    }
    function lihatPerjanjian(id){
        $('#detail_transaksi').load('{{url("admin/transaksi/detail")}}/'+id, function(e) {});
    }
</script>

@section('scripts')
@parent

@endsection